### ISSUE TITLE
Can't download image from API Url (localhost)

### ISSUE THREAD

**Issue by zgramming** [ko2ic/image_downloader#51] opened 2019-10-03 13:27 UTC
Hello, i got some problem with download image from API Url. I have Url like this **http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg**, I can see the image but when i try download it ,my console give me infinite loop like this and my image not downloaded : 
```
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
D/image_downloader(21091): RequestResult(id=798, remoteUri=http://192.168.43.159/flutter-news/images/berita/92dae9b51087d930a32aff53eaded163.jpg, localUri=null, mediaType=null, totalSize=-1, title=, description=)
D/image_downloader(21091): 0
Application finished.
Exited (sigterm)
```
My simple download code like this : 
```
Future testingDownloadImage(String imageUrl) async {
    try {
      var imageId =
          await ImageDownloader.downloadImage('$baseURLimage/berita/$imageUrl');
      if (imageId == null) {
        print('Image Kosong');
      }
      var fileName = await ImageDownloader.findName(imageId);
      var path = await ImageDownloader.findPath(imageId);
      var size = await ImageDownloader.findByteSize(imageId);
      var mimeType = await ImageDownloader.findMimeType(imageId);
      print(imageId);
      print(fileName);
      print(path);
      print(size);
      print(mimeType);
    } catch (e) {
      print(e);
      return null;
    }
  }
```
**Main.dart**
```
void _testingDownloadImage(String imageUrl) async {
    var downloadImage = api.testingDownloadImage(imageUrl);
    print(downloadImage);
    if (downloadImage != null) {
      print('success');
    } else {
      print('failed');
    }
  }
 IconButton(
                                    onPressed: () => _testingDownloadImage(
                                        widget.gambarBerita),
                                    icon: Icon(Icons.save),
                                  ),
```
I'm already read this issue :
[Github Issue 400](https://github.com/ko2ic/image_downloader/issues/47)
[Stackoverflow](https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie.)

but result is nothing,I'm mistake something ?
>Btw , if i'm using default Url documentation [Image Default](https://raw.githubusercontent.com/wiki/ko2ic/image_downloader/images/flutter.png), Everything it's ok.

**Comment by wyklif** [comment] 2019-10-06 18:43
also facing this issue, however when i started building my app it was working

**Comment by wyklif** [comment] 2019-10-06 19:09
i just found out that i was passing a wrong value for url, print out your url and see what you are actually passing to the downloader @zgramming

**Comment by ko2ic** [comment] 2019-10-12 11:02
I tried writing the following nodejs.

```js
var app = express();
app.get('/*.(png|bmp|jpg|jpeg)', function (req, res) {
        console.log(req.url);
        res.sendFile(path.resolve('./images/'+req.url));
    });
```

```
$ tree images
images
└── flutter.jpg
```

In this example project, I confirmed the operation with the following URL on Android. 
It works without problems.

```dart
_downloadImage("http://10.0.2.2:3000/flutter.jpg");
```

**Comment by HTMHell** [comment] 2019-10-17 11:56
That's probably happening because you are not downloading from HTTPS. Look at: https://github.com/ko2ic/image_downloader/issues/47

**Comment by ko2ic** [comment] 2019-12-07 15:20
Close it because it has been confirmed that it works without problems.

**Closed by ko2ic** 2019-12-07 15:20 UTC

**Comment by gaoobin** [comment] 2020-07-28 03:22
What is the solution, I also encountered this problem

**Comment by gaoobin** [comment] 2020-07-28 03:23
> Close it because it has been confirmed that it works without problems.

What is the solution, I also encountered this problem
